/**
 * Blueprint Types & Interfaces
 * Story: SPRINT-1-P1 (Blueprint Persistence)
 */

export type Language = 'en' | 'pt-BR';
export type BlueprintStatus = 'generated' | 'sent' | 'opened';
export type EmailJobStatus = 'pending' | 'sent' | 'failed' | 'retrying';

/**
 * Core Blueprint Data Structure
 */
export interface Blueprint {
  id: string; // UUID
  session_id: string; // UUID for anon tracking
  user_id: string | null; // UUID, filled after auth
  email: string;
  name: string;
  phone?: string;
  company?: string;
  role?: string;
  content: BlueprintContent;
  language: Language;
  status: BlueprintStatus;
  created_at: string; // ISO timestamp
  updated_at: string; // ISO timestamp
}

/**
 * Blueprint Content (generated by AI)
 */
export interface BlueprintContent {
  title: string;
  executive_summary: string;
  problem_statement: string;
  current_state_analysis: string;
  proposed_solution: string;
  architecture_layers: ArchitectureLayer[];
  technology_stack: TechnologyChoice[];
  implementation_timeline: TimelineItem[];
  risks_and_mitigations: RiskMitigation[];
  success_metrics: SuccessMetric[];
  // Optionally include technical architecture (can be hidden from frontend)
  technicalArchitecture?: string;
}

export interface ArchitectureLayer {
  name: string;
  components: string[];
  technologies: string[];
  responsibilities: string[];
}

export interface TechnologyChoice {
  category: string;
  selected: string;
  alternatives: string[];
  rationale: string;
  risk_level: 'low' | 'medium' | 'high';
}

export interface TimelineItem {
  phase: string;
  duration: string;
  deliverables: string[];
  dependencies: string[];
}

export interface RiskMitigation {
  risk: string;
  probability: 'low' | 'medium' | 'high';
  impact: 'low' | 'medium' | 'high';
  mitigation_strategy: string;
}

export interface SuccessMetric {
  metric: string;
  baseline: string;
  target: string;
  measurement_method: string;
}

/**
 * Email Job for Queue Processing
 */
export interface EmailJob {
  id: string; // UUID
  blueprint_id: string; // UUID
  recipient_email: string;
  pdf_url: string | null;
  template: string; // 'blueprint_delivery', 'follow_up', etc
  subject: string;
  status: EmailJobStatus;
  retry_count: number;
  last_error: string | null;
  last_attempt_at: string | null;
  sent_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Email Delivery Log
 */
export interface EmailDeliveryLog {
  id: string;
  email_job_id: string;
  event: 'sent' | 'failed' | 'retrying' | 'bounce' | 'complaint';
  status_code: number | null;
  error_message: string | null;
  resend_message_id: string | null;
  created_at: string;
}

/**
 * Request/Response Types
 */
export interface SaveBlueprintRequest {
  session_id: string;
  user_id?: string; // Optional, filled if already authed
  email: string;
  name: string;
  phone?: string;
  company?: string;
  role?: string;
  blueprint: BlueprintContent;
  language: Language;
}

export interface SaveBlueprintResponse {
  success: boolean;
  blueprint_id?: string;
  pdf_url?: string;
  message: string;
  error?: string;
}

export interface ProcessEmailQueueResponse {
  total_processed: number;
  sent_count: number;
  failed_count: number;
  retry_count: number;
  timestamp: string;
}

/**
 * Blueprint Audit Log
 */
export interface BlueprintAuditLog {
  id: string;
  blueprint_id: string;
  action: 'created' | 'updated' | 'deleted';
  user_id: string | null;
  session_id: string;
  changes: Record<string, any>;
  created_at: string;
}

/**
 * PDF Generation Options
 */
export interface PDFGenerationOptions {
  blueprint: BlueprintContent;
  language: Language;
  recipient_name: string;
  format: 'a4' | 'letter';
  orientation: 'portrait' | 'landscape';
}

export interface PDFGenerationResult {
  success: boolean;
  buffer?: Buffer;
  url?: string;
  error?: string;
  size_bytes?: number;
}

/**
 * Email Template Data
 */
export interface EmailTemplateData {
  recipient_name: string;
  recipient_email: string;
  blueprint_title: string;
  blueprint_summary: string;
  pdf_url: string;
  download_expires_at: string;
  language: Language;
  dashboard_url: string;
  unsubscribe_url: string;
}

/**
 * Validation Results
 */
export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
}

export interface ValidationError {
  field: string;
  message: string;
  code: string;
}
